### ISSUE TITLE
Deinterlacing Issue with Beetle-PSX

### ISSUE THREAD

**Issue by ichee** [libretro/slang-shaders#252]
The `Bob-Deinterlacing` shader is causing uneven shaking and squishing of the screen when vsync is disabled.
Everything seems to be fine if vsync is enabled, except for vsync being enabled.

Tested with latest nightly of Retroarch and Beetle-PSX, though older versions have the same behavior.
Using Software only build.
Both interpreters and dynarec tested.

Video Driver: vulkan, d3d11, and glcore tested

Running Exclusive Fullscreen.

Windows 11
Nvidia RTX 3090

vsync off:

![vsync-off](https://user-images.githubusercontent.com/22252639/168792391-a3d7a856-73ed-4fc9-9d46-5344f95c4d95.png)

vsync on:

![vsync-on](https://user-images.githubusercontent.com/22252639/168790986-08282a8d-8fd5-4072-a596-7718320cfbdb.png)

**Comment by hizzlekizzle** [comment]
Yes, if it's not in sync with your monitor refresh, it's going to look weird. Enabling the frame-blending parameter should smooth it out, though, I think, if you don't want to use vsync.

**Comment by ichee** [comment]
Frame-blending doesn't address the issue, and setting the refresh rate to 59.94hz still doesn't prevent it. Even setting my display to a custom created refresh rate of 59.83hz doesn't resolve it, even though that rate would just be for progressive video.

Just to clarify, the first image above is dynamically shifting and is not static (screenshots don't really do it justice).

I'd imagine this issue would be much more problematic with variable refresh rate displays since vsync would be best left disabled.

Partially related, but any way a deinterlacing option could be integrated into the software core itself?
I've noticed some core options have less issues than their shader equivalents.

**Comment by hizzlekizzle** [comment]
I believe VRR in RetroArch requires vsync ON.

Using a filter in the core will also produce the same jittering in this case because it's a matter of uneven frame times due to disabling vsync. AFAIK, one of the reasons the woven deinterlacing is used in emulators is because it isn't affected by exact frame sync the way bobbing is, and I don't think there's any point where the core creates a 480p image that we could tap into before it is then split into 480i, so *some* sort of deinterlacing (be it weave or bob or whatever) has to occur.

**Comment by nfp0** [comment]
Yes, I believe you need Vsync enabled for VRR to work on RetroArch. That was written on the blog somewhere, but I believe it should be added to the menu description too, as VRR is typically used without Vsync in most normal games. Or maybe even hide the setting if Vsync is disabled.

@ichee You will always need to be synced with your monitor's refresh rate if you want bob-deinterlacing, otherwise it will never look good. On RetroArch that means leaving Vsync on.
I use bob-deinterlacing myself too.

**Comment by ichee** [comment]
Been messing around with this a bit and it seems fixable by not only disabling vsync in Retroarch, but also forcing it off in the nvidia control panel.

No idea why forcing it off there helps when it was set to application controlled. The behavior appears different with vulkan compared to d3d11. Vulkan works fine with the above adjustment, but not d3d11 or opengl.

Maybe it's another nvidia thing or a Windows thing.
Either way, this is viable now with deinterlacing and no vsync.
