### ISSUE TITLE
[ares/librashader] Excessively bright colors with CRT-Hylian shaders 

### ISSUE THREAD

**Issue by kev4cards** [libretro/slang-shaders#552]
CRT-Hylian appears to not be working properly with ares and librashader. There are at least a few other CRT-Hylian based shaders that are showing this same color problem.

ares output set to Best Fit (scaled):
![Donkey-Kong-Country-3-SNES_best-fit-scaled_ares_crt-hylian-shader](https://github.com/libretro/slang-shaders/assets/21962903/ad6591c5-9717-4564-af0b-9de4d05b69e5)
ares output set to Integer (scaled):
![Donkey-Kong-Country-3-SNES_integer-scaled_ares_crt-hylian-shader](https://github.com/libretro/slang-shaders/assets/21962903/5c12e0a9-615c-422e-b422-af903f86286b)
RetroArch bsnes (output video glcore) integer scaling OFF:
![Donkey-Kong-Country-3-SNES_no-integer-scaling_bsnes-core-RA-glcore-output_crt-hylian-shader](https://github.com/libretro/slang-shaders/assets/21962903/370900ce-8526-4fbe-858d-d6fcb52fa309)
RetroArch bsnes (output video glcore) integer scaling ON:
![Donkey-Kong-Country-3-SNES_integer-scaling_bsnes-core-RA-glcore-output_crt-hylian-shader](https://github.com/libretro/slang-shaders/assets/21962903/9432cbff-fabc-4023-bb5d-67ec0cb7a323)

My system specs:
OS: Windows 11 23H2
CPU: Intel i7-9750H
GPU: NVIDIA GTX 1660 Ti
GPU Driver: 551.52
RAM: 16 GB DDR4 2666 MHz

**Comment by hizzlekizzle** [comment]
Yeah, definitely something wonky going on there. Got any ideas, @hyllian?

**Comment by Hyllian** [comment]
Looks like it's working on Retroarch. So, why did you assume the problem is in the shader?

**Comment by chyyran** [comment]
Yeah this is not an issue with the shader. Will be fixed by https://github.com/SnowflakePowered/librashader/pull/71. 

In the future I would suggest librashader-related issues get reported there first for triage as to not bother shader authors. RetroArch is the reference implementation so if it works there it should be considered a bug for downstream implementations.

**Comment by hizzlekizzle** [comment]
I had asked them to report it here as well, in case it was an actual upstream problem, but I guess for at least a while it would make sense to start downstream.

I just didn't want you to have to do a bunch of weird workarounds for (hypothetical) objectively incorrect behavior, such as the looser preset parsing you mentioned on ares discord. That sort of thing we definitely want to take care of upstream rather than cause problems for everyone else :)

**Comment by chyyran** [comment]
A good rule of thumb is that rendering differences are almost always librashader bugs, but if the preset doesn’t load in librashader but does in RetroArch then its probably a syntax error upstream.

If it does properly load well enough to get an image, the pipeline is close enough to what RetroArch does that it shouldn’t have any visible rendering differences.

**Comment by kev4cards** [comment]
Since the issue has been addressed, I will close this out and will look to triage in the ares Discord server first in order to have the bug pointed to the right project of the three involved.
